export const projects = [
  {
    id: 1,
    category: "web",
    title: "Portfolio Website",
    description: "A personal portfolio showcasing my projects.",
    image: "./src/images/placeholder.png",
    tags: ["React.js", "Frontend"],
    details: "This is a detailed description of the Portfolio Website project.",
    github: "https://github.com/example",
  },
  {
    id: 2,
    category: "web",
    title: "E-Commerce",
    description: "A small-scale platform with a shopping cart, user authentication, and a mock payment system.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 3,
    category: "web",
    title: "Ticketing System",
    description: "Site for maintaining and processing tickets for an IT team and their customers.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 4,
    category: "software",
    title: "Time Management App",
    description: "An automatic time tracking app for workplace productivity.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 5,
    category: "software",
    title: "Chat Application",
    description: "A secure instant messaging application.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 6,
    category: "software",
    title: "Password Manager",
    description: "An application for securely storing, manging, and accessing passwords.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 7,
    category: "security",
    title: "Network Monitoring Tool",
    description: "A Python-based tool to monitor active devices, bandwidth, and latency.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 8,
    category: "security",
    title: "Network Monitoring Tool",
    description: "Create a user-friendly interface for a VPN setup using OpenVPN or WireGuard.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 9,
    category: "security",
    title: "Vulnerability Scanner",
    description: "A tool to identify common web app vulnerabilities using Python and OWASP ZAP.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 10,
    category: "graphic",
    title: "IT Service Desk Posters",
    description: "Posters designed for the IT Service Desk at SUNY Cobleskill.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 11,
    category: "graphic",
    title: "Startup Branding Kit",
    description: "Branding kit for a theoretical startup brand based on one of my projects.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 12,
    category: "graphic",
    title: "Cybersecurity Infographic",
    description: "An easy to read infographic informing people about best security practices in the workplace.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 13,
    category: "graphic",
    title: "Social Media Campaign",
    description: "Graphics for promoting a tech product or service on Instagram and LinkedIn.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 14,
    category: "graphic",
    title: "Typography Posters",
    description: "A visually striking typographic poster with a tech-related quote.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 15,
    category: "graphic",
    title: "Digital Illustration",
    description: "A futuristic or tech-themed artwork to showcase creativity.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 16,
    category: "modeling",
    title: "3D Tech Gadget",
    description: "Create a detailed 3D model of a fictional smartphone, smartwatch, or VR headset.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 17,
    category: "modeling",
    title: "Computer Hardware Visualization",
    description: "Model and render components of a PC (e.g., GPU, CPU, motherboard).",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 18,
    category: "modeling",
    title: "Low-Poly Environment",
    description: "A low-poly 3D scene of a tech-themed world, like a futuristic city.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 19,
    category: "modeling",
    title: "Character Design",
    description: "Model a tech-inspired character or robot with moving parts.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
  {
    id: 20,
    category: "modeling",
    title: "3D Typography",
    description: "Design a tech-related quote in 3D typography with textures and effects.",
    image: "./images/placeholder.png",
    tags: ["Node.js", "Backend"],
    details: "This is a detailed description.",
    github: "https://github.com/example",
  },
];


  